ALTER TABLE kevin ADD COLUMN want INTEGER DEFAULT 0;
ALTER TABLE kevin ADD COLUMN want_price INTEGER;
ALTER TABLE kevin ADD COLUMN want_at TEXT;
ALTER TABLE kevin ADD COLUMN verdict TEXT;
ALTER TABLE games ADD COLUMN matched_at TEXT;
